require('dotenv').config();
import { Request, Response } from 'express';
import dataStore from '../dataStore';

export const chat = async (req: Request, res: Response) => {
  const { faqId, query } = req.body;

  try {
    const faqAnswer = dataStore.faqAnswers.find(answer => answer.id === faqId)
    if (!faqAnswer) {
      return res.json({ data: "This answer git will be generated by LLM model but currently open api is not working" })
    }
    
    res.json({ data: faqAnswer.answer });
  } catch (error) {
    res.status(500).json({ error: 'Failed to generate response' });
  }
};
